### PR TITLE
Backport HttpProvider changes from web3.js to fix handling server-side errors

### LINKED ISSUE #637: Make error more specific
There is some cases we got error like below, but it is too broad what is the exact reason of this.
```
Error: Invalid JSON RPC response: ""
```

It would be good if we make the error more specific.

1. Need to find the reason of this error
2. Need to find ways to distinguish the error message based on the exact reason.

### PR DESCRIPTION
**Pull request by ayanamidev**
closes #637

Backported changes from PR https://github.com/ChainSafe/web3.js/pull/5085 https://github.com/ChainSafe/web3.js/pull/5179 to fix handling server-side errors that return timeouts, rate limits ( 429 ), etc.

### CODE REVIEW

**Comment by ayanamidev** [comment]
Capture

Working as intended I think

File: test/invalidResponse.js [hunk 1]
```diff
@@ -40,7 +40,7 @@ describe('Invalid response test', () => {
             await caver.klay.getNodeInfo()
             assert(false)
         } catch (err) {
-            expect(err.message).to.equals('Invalid JSON RPC response: ""')
+            expect(err.message).to.equals("CONNECTION ERROR: Couldn't connect to node http://localhost:1234/.")
```
Comment (jimni1222) [inline test/invalidResponse.js:43]: Can you change the test description also?

File: types/packages/caver-core-requestmanager/caver-providers-http/src/index.d.ts [hunk 2]
```diff
@@ -50,7 +49,6 @@ export class HttpProvider {
     headers?: HttpHeader[]
     agent?: HttpProviderAgent
 
-    _prepareRequest?(): any
```
Comment (jimni1222) [inline types/packages/caver-core-requestmanager/caver-providers-http/src/index.d.ts:53]: Maybe `baseUrl` field should be removed in `HttpProviderAgent`?

**Comment by jimni1222** [comment]
@nazarhussain Hi, Nazarhussain

**Comment by ayanamidev** [comment]
@jimni1222 Since he is the maintainer of the web3.js project, I could reset the git author if necessary.

**Comment by jimni1222** [comment]
@ayanamidev Could you please reset the git author then? Because of that commit, i cannot merge this.

**Comment by ayanamidev** [comment]
@jimni1222 Done.

**Review by jimni1222 — APPROVED** [review]
LGTM =) Thank you for your contribution

**Comment by nazarhussain** [comment]
@jimni1222 I had signed the CLA,
