### PR TITLE
Fixed error message and duplicate rejection

### LINKED ISSUE #147: Wrong error message on malformed transaction
**Describe the bug**

```
 Error: Only Legacy transactions can be signed on a Klaytn node!
```

**How to reproduce**
There are two ways to reproduce this bug:

* Works perfrect with attached code (may occurs an error since the account does not have any KLAY)
* Case1: Change `feePayer` to `        feePayer: '0xad7c07eab1e56fbbb976fd5377e5088ec5528cd9'`
* Case2: Uncomment `//gasPrice: '999999999999999',`

**Expected behavior**
The error message should indicate exactly what went wrong.

**Attachments**

```
"caver-js": {
      "version": "1.2.0",
```
```js
const Caver = require('caver-js');

const caver = new Caver('https://api.baobab.klaytn.net:8651/');
const cred = require('./cred.json');

caver.klay.getNodeInfo().then(console.log);

caver.klay.accounts.wallet.add('0x5849a0f62008833b708af0bf4886e5deec0ea51bb405bf02a7ed79d4c43e5797');
caver.klay.accounts.wallet.add({
    address: "0x48649c3beb3e5abf532b0626ce72c27cb64e012f",
    privateKey: "0x7b04975dea529019127697fb267a72e2bb3c26c3e85ae358864baa84a2b56d47"
});

const contract = new caver.klay.Contract(require('./abi.json'), '0xcd7589F4641B6d7f7f9ab08bA1d4fB5985658A0a', {
    from: cred.address,
    gasPrice: '25000000000'
});


async function createTx(tx) {
    const account = caver.klay.accounts.wallet[0];
    tx.from = account.address;
    console.log(account.address);
    const signed = await account.signTransaction(tx);
    console.log(signed);
    return signed.rawTransaction;
}

async function test() {
    const input = contract.methods.voteMob("test", 0, 0).encodeABI();
    const tx = await createTx({
        type: 'FEE_DELEGATED_SMART_CONTRACT_EXECUTION',
        to: '0xcd7589F4641B6d7f7f9ab08bA1d4fB5985658A0a',
        //gasPrice: '999999999999999',
        value: '0',
        data: input,
        gas: 900000
    });

    const resp = await caver.klay.sendTransaction({
        senderRawTransaction: tx.toString(),
        feePayer: '0x48649c3beb3e5abf532b0626ce72c27cb64e012f',
    });

    console.log(resp);
}

test();
```

### PR DESCRIPTION
**Pull request by jimni1222**
## Proposed changes

This PR introduces fixing error message(Error: Only Legacy transactions can be signed on a Klaytn node!) to help developers to figure out cause of problem.

And also duplicate Promise reject is removed.
'sendTxCallback' will reject when error, so Promise.reject doesn't need to be call again after that.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/caver-js/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/caver-js)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

close #147 

## Further comments

If there is a better opinion of the error message, i will reflect it.

### CODE REVIEW

File: packages/caver-core-method/src/index.js [hunk 1]
```diff
@@ -348,15 +347,17 @@ const buildSendRequestFunc = (defer, sendSignedTx, sendTxCallback) => (payload,
                 // If wallet was not found in caver-js wallet, then it has to use wallet in Node.
                 // Signing to transaction using wallet in Node supports only LEGACY transaction, so if transaction is not LEGACY, return error.
                 if (tx.feePayer !== undefined || (tx.type !== undefined && tx.type !== 'LEGACY')) {
-                    error = new Error('Only Legacy transactions can be signed on a Klaytn node!')
+                    error = new Error(
+                        `Failed to send transaction: Only Legacy transactions can be signed on a Klaytn node. Please add an account(${addressToUse}) with caver.klay.accounts.wallet.add, or use a 'LEGACY' transaction.`
```
Comment (kjhman21) [inline packages/caver-core-method/src/index.js]: ERROR: no private key found in the caver-js wallet. Trying to use the Klaytn node's wallet, but it only supports legacy transactions. Please add private key of ${addressToUse} to the caver-js wallet.

Please change the error statements like above.

Comment (jimni1222) [reply packages/caver-core-method/src/index.js]: Error message is edited :) Thank you!

File: packages/caver-core-method/src/index.js [hunk 2]
```diff
@@ -348,15 +347,17 @@ const buildSendRequestFunc = (defer, sendSignedTx, sendTxCallback) => (payload,
                 // If wallet was not found in caver-js wallet, then it has to use wallet in Node.
                 // Signing to transaction using wallet in Node supports only LEGACY transaction, so if transaction is not LEGACY, return error.
                 if (tx.feePayer !== undefined || (tx.type !== undefined && tx.type !== 'LEGACY')) {
-                    error = new Error('Only Legacy transactions can be signed on a Klaytn node!')
+                    error = new Error(
+                        `no private key found in the caver-js wallet. Trying to use the Klaytn node's wallet, but it only supports legacy transactions. Please add private key of ${addressToUse} to the caver-js wallet.`
```
Comment (kjhman21) [inline packages/caver-core-method/src/index.js]:
```suggestion
                        `No private key found in the caver-js wallet. Trying to use the Klaytn node's wallet, but it only supports legacy transactions. Please add private key of ${addressToUse} to the caver-js wallet.`
```

Sorry, but please use a capital letter if it comes to the first.
